In [6]:
import yaml
from util.config_utils import load_yaml

cfg = load_yaml('configs/rule_loss.yaml')

cfg.rules.__dict__

{'name': '8693_full',
 'mode': 'soft',
 'recall_threshold': 0.8,
 'constraint_weight': 1}

In [4]:
import numpy as np
prec = np.array([1,2,3,4,5])
print(prec)
print(prec[None, :])

vals = np.array([[1,0,0,1,0],
                 [0,1,0,1,1]])
mask = vals.astype(bool)

result = np.where(mask, prec[None, :], 0)

print(result)



[1 2 3 4 5]
[[1 2 3 4 5]]
[[1 0 0 4 0]
 [0 2 0 4 5]]
